name = "duckmail-cloudflare-provider"
main = "worker.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "temp_mail_db"
database_id = "70bece35-d5bf-487b-9730-c7546f0266c3"

[vars]
MAIL_DOMAIN = "10xco.de"
JWT_TOKEN = "tusiKCfuyXrwDPrsP77GHZtSSdMux6AqDZQKmySpBss="
# Optional: RESEND_API_KEY = "<your-resend-api-key>"

# If you want to test locally with wrangler dev
[env.development.vars]
MAIL_DOMAIN = "test.local"
JWT_TOKEN = "development-secret-key" 